# experiment (i) cart-pole
python run.py --utility_function="PAML" --seed=1 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --utility_function="PAML" --seed=2 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --utility_function="PAML" --seed=3 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --utility_function="PAML" --seed=4 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --utility_function="PAML" --seed=5 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --utility_function="PAML" --seed=6 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --utility_function="PAML" --seed=7 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --utility_function="PAML" --seed=8 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --utility_function="PAML" --seed=9 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --utility_function="PAML" --seed=10 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --utility_function="UNI" --seed=1 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --utility_function="UNI" --seed=2 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --utility_function="UNI" --seed=3 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --utility_function="UNI" --seed=4 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --utility_function="UNI" --seed=5 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --utility_function="UNI" --seed=6 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --utility_function="UNI" --seed=7 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --utility_function="UNI" --seed=8 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --utility_function="UNI" --seed=9 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --utility_function="UNI" --seed=10 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --utility_function="LHS" --seed=1 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --utility_function="LHS" --seed=2 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --utility_function="LHS" --seed=3 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --utility_function="LHS" --seed=4 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --utility_function="LHS" --seed=5 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --utility_function="LHS" --seed=6 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --utility_function="LHS" --seed=7 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --utility_function="LHS" --seed=8 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --utility_function="LHS" --seed=9 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --utility_function="LHS" --seed=10 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --oracle True --seed=1 --task_budget=0 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --oracle True --seed=2 --task_budget=0 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --oracle True --seed=3 --task_budget=0 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --oracle True --seed=4 --task_budget=0 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --oracle True --seed=5 --task_budget=0 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --oracle True --seed=6 --task_budget=0 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --oracle True --seed=7 --task_budget=0 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --oracle True --seed=8 --task_budget=0 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --oracle True --seed=9 --task_budget=0 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --oracle True --seed=10 --task_budget=0 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.

# experiment (i) pendubot
python run.py --utility_function="PAML" --seed=1 --env_name="pendubot" --dt=.05 --alternations=5 --training_steps=5000 --n_initial_training_envs=4 --config_interval_lower_bound_dim_1=.6 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.6 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="PAML" --seed=2 --env_name="pendubot" --dt=.05 --alternations=5 --training_steps=5000 --n_initial_training_envs=4 --config_interval_lower_bound_dim_1=.6 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.6 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="PAML" --seed=3 --env_name="pendubot" --dt=.05 --alternations=5 --training_steps=5000 --n_initial_training_envs=4 --config_interval_lower_bound_dim_1=.6 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.6 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="PAML" --seed=4 --env_name="pendubot" --dt=.05 --alternations=5 --training_steps=5000 --n_initial_training_envs=4 --config_interval_lower_bound_dim_1=.6 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.6 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="PAML" --seed=5 --env_name="pendubot" --dt=.05 --alternations=5 --training_steps=5000 --n_initial_training_envs=4 --config_interval_lower_bound_dim_1=.6 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.6 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="PAML" --seed=6 --env_name="pendubot" --dt=.05 --alternations=5 --training_steps=5000 --n_initial_training_envs=4 --config_interval_lower_bound_dim_1=.6 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.6 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="PAML" --seed=7 --env_name="pendubot" --dt=.05 --alternations=5 --training_steps=5000 --n_initial_training_envs=4 --config_interval_lower_bound_dim_1=.6 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.6 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="PAML" --seed=8 --env_name="pendubot" --dt=.05 --alternations=5 --training_steps=5000 --n_initial_training_envs=4 --config_interval_lower_bound_dim_1=.6 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.6 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="PAML" --seed=9 --env_name="pendubot" --dt=.05 --alternations=5 --training_steps=5000 --n_initial_training_envs=4 --config_interval_lower_bound_dim_1=.6 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.6 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="PAML" --seed=10 --env_name="pendubot" --dt=.05 --alternations=5 --training_steps=5000 --n_initial_training_envs=4 --config_interval_lower_bound_dim_1=.6 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.6 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="UNI" --seed=1 --env_name="pendubot" --dt=.05 --alternations=5 --training_steps=5000 --n_initial_training_envs=4 --config_interval_lower_bound_dim_1=.6 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.6 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="UNI" --seed=2 --env_name="pendubot" --dt=.05 --alternations=5 --training_steps=5000 --n_initial_training_envs=4 --config_interval_lower_bound_dim_1=.6 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.6 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="UNI" --seed=3 --env_name="pendubot" --dt=.05 --alternations=5 --training_steps=5000 --n_initial_training_envs=4 --config_interval_lower_bound_dim_1=.6 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.6 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="UNI" --seed=4 --env_name="pendubot" --dt=.05 --alternations=5 --training_steps=5000 --n_initial_training_envs=4 --config_interval_lower_bound_dim_1=.6 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.6 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="UNI" --seed=5 --env_name="pendubot" --dt=.05 --alternations=5 --training_steps=5000 --n_initial_training_envs=4 --config_interval_lower_bound_dim_1=.6 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.6 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="UNI" --seed=6 --env_name="pendubot" --dt=.05 --alternations=5 --training_steps=5000 --n_initial_training_envs=4 --config_interval_lower_bound_dim_1=.6 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.6 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="UNI" --seed=7 --env_name="pendubot" --dt=.05 --alternations=5 --training_steps=5000 --n_initial_training_envs=4 --config_interval_lower_bound_dim_1=.6 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.6 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="UNI" --seed=8 --env_name="pendubot" --dt=.05 --alternations=5 --training_steps=5000 --n_initial_training_envs=4 --config_interval_lower_bound_dim_1=.6 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.6 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="UNI" --seed=9 --env_name="pendubot" --dt=.05 --alternations=5 --training_steps=5000 --n_initial_training_envs=4 --config_interval_lower_bound_dim_1=.6 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.6 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="UNI" --seed=10 --env_name="pendubot" --dt=.05 --alternations=5 --training_steps=5000 --n_initial_training_envs=4 --config_interval_lower_bound_dim_1=.6 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.6 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="LHS" --seed=1 --env_name="pendubot" --dt=.05 --alternations=5 --training_steps=5000 --n_initial_training_envs=4 --config_interval_lower_bound_dim_1=.6 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.6 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="LHS" --seed=2 --env_name="pendubot" --dt=.05 --alternations=5 --training_steps=5000 --n_initial_training_envs=4 --config_interval_lower_bound_dim_1=.6 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.6 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="LHS" --seed=3 --env_name="pendubot" --dt=.05 --alternations=5 --training_steps=5000 --n_initial_training_envs=4 --config_interval_lower_bound_dim_1=.6 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.6 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="LHS" --seed=4 --env_name="pendubot" --dt=.05 --alternations=5 --training_steps=5000 --n_initial_training_envs=4 --config_interval_lower_bound_dim_1=.6 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.6 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="LHS" --seed=5 --env_name="pendubot" --dt=.05 --alternations=5 --training_steps=5000 --n_initial_training_envs=4 --config_interval_lower_bound_dim_1=.6 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.6 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="LHS" --seed=6 --env_name="pendubot" --dt=.05 --alternations=5 --training_steps=5000 --n_initial_training_envs=4 --config_interval_lower_bound_dim_1=.6 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.6 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="LHS" --seed=7 --env_name="pendubot" --dt=.05 --alternations=5 --training_steps=5000 --n_initial_training_envs=4 --config_interval_lower_bound_dim_1=.6 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.6 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="LHS" --seed=8 --env_name="pendubot" --dt=.05 --alternations=5 --training_steps=5000 --n_initial_training_envs=4 --config_interval_lower_bound_dim_1=.6 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.6 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="LHS" --seed=9 --env_name="pendubot" --dt=.05 --alternations=5 --training_steps=5000 --n_initial_training_envs=4 --config_interval_lower_bound_dim_1=.6 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.6 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="LHS" --seed=10 --env_name="pendubot" --dt=.05 --alternations=5 --training_steps=5000 --n_initial_training_envs=4 --config_interval_lower_bound_dim_1=.6 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.6 --config_interval_upper_bound_dim_2=3.
python run.py --oracle True --task_budget=0 --seed=1 --env_name="pendubot" --dt=.05 --alternations=5 --training_steps=5000 --n_initial_training_envs=4 --config_interval_lower_bound_dim_1=.6 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.6 --config_interval_upper_bound_dim_2=3.
python run.py --oracle True --task_budget=0 --seed=2 --env_name="pendubot" --dt=.05 --alternations=5 --training_steps=5000 --n_initial_training_envs=4 --config_interval_lower_bound_dim_1=.6 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.6 --config_interval_upper_bound_dim_2=3.
python run.py --oracle True --task_budget=0 --seed=3 --env_name="pendubot" --dt=.05 --alternations=5 --training_steps=5000 --n_initial_training_envs=4 --config_interval_lower_bound_dim_1=.6 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.6 --config_interval_upper_bound_dim_2=3.
python run.py --oracle True --task_budget=0 --seed=4 --env_name="pendubot" --dt=.05 --alternations=5 --training_steps=5000 --n_initial_training_envs=4 --config_interval_lower_bound_dim_1=.6 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.6 --config_interval_upper_bound_dim_2=3.
python run.py --oracle True --task_budget=0 --seed=5 --env_name="pendubot" --dt=.05 --alternations=5 --training_steps=5000 --n_initial_training_envs=4 --config_interval_lower_bound_dim_1=.6 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.6 --config_interval_upper_bound_dim_2=3.
python run.py --oracle True --task_budget=0 --seed=6 --env_name="pendubot" --dt=.05 --alternations=5 --training_steps=5000 --n_initial_training_envs=4 --config_interval_lower_bound_dim_1=.6 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.6 --config_interval_upper_bound_dim_2=3.
python run.py --oracle True --task_budget=0 --seed=7 --env_name="pendubot" --dt=.05 --alternations=5 --training_steps=5000 --n_initial_training_envs=4 --config_interval_lower_bound_dim_1=.6 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.6 --config_interval_upper_bound_dim_2=3.
python run.py --oracle True --task_budget=0 --seed=8 --env_name="pendubot" --dt=.05 --alternations=5 --training_steps=5000 --n_initial_training_envs=4 --config_interval_lower_bound_dim_1=.6 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.6 --config_interval_upper_bound_dim_2=3.
python run.py --oracle True --task_budget=0 --seed=9 --env_name="pendubot" --dt=.05 --alternations=5 --training_steps=5000 --n_initial_training_envs=4 --config_interval_lower_bound_dim_1=.6 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.6 --config_interval_upper_bound_dim_2=3.
python run.py --oracle True --task_budget=0 --seed=10 --env_name="pendubot" --dt=.05 --alternations=5 --training_steps=5000 --n_initial_training_envs=4 --config_interval_lower_bound_dim_1=.6 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.6 --config_interval_upper_bound_dim_2=3.

# experiment (i) cart-double-pole
python run.py --utility_function="PAML" --seed=1 --env_name="cartdoublepole" --dt=.05 --alternations=10 --training_steps=7000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="PAML" --seed=2 --env_name="cartdoublepole" --dt=.05 --alternations=10 --training_steps=7000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="PAML" --seed=3 --env_name="cartdoublepole" --dt=.05 --alternations=10 --training_steps=7000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="PAML" --seed=4 --env_name="cartdoublepole" --dt=.05 --alternations=10 --training_steps=7000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="PAML" --seed=5 --env_name="cartdoublepole" --dt=.05 --alternations=10 --training_steps=7000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="PAML" --seed=6 --env_name="cartdoublepole" --dt=.05 --alternations=10 --training_steps=7000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="PAML" --seed=7 --env_name="cartdoublepole" --dt=.05 --alternations=10 --training_steps=7000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="PAML" --seed=8 --env_name="cartdoublepole" --dt=.05 --alternations=10 --training_steps=7000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="PAML" --seed=9 --env_name="cartdoublepole" --dt=.05 --alternations=10 --training_steps=7000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="PAML" --seed=10 --env_name="cartdoublepole" --dt=.05 --alternations=10 --training_steps=7000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="UNI" --seed=1 --env_name="cartdoublepole" --dt=.05 --alternations=10 --training_steps=7000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="UNI" --seed=2 --env_name="cartdoublepole" --dt=.05 --alternations=10 --training_steps=7000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="UNI" --seed=3 --env_name="cartdoublepole" --dt=.05 --alternations=10 --training_steps=7000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="UNI" --seed=4 --env_name="cartdoublepole" --dt=.05 --alternations=10 --training_steps=7000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="UNI" --seed=5 --env_name="cartdoublepole" --dt=.05 --alternations=10 --training_steps=7000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="UNI" --seed=6 --env_name="cartdoublepole" --dt=.05 --alternations=10 --training_steps=7000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="UNI" --seed=7 --env_name="cartdoublepole" --dt=.05 --alternations=10 --training_steps=7000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="UNI" --seed=8 --env_name="cartdoublepole" --dt=.05 --alternations=10 --training_steps=7000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="UNI" --seed=9 --env_name="cartdoublepole" --dt=.05 --alternations=10 --training_steps=7000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="UNI" --seed=10 --env_name="cartdoublepole" --dt=.05 --alternations=10 --training_steps=7000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="LHS" --seed=1 --env_name="cartdoublepole" --dt=.05 --alternations=10 --training_steps=7000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="LHS" --seed=2 --env_name="cartdoublepole" --dt=.05 --alternations=10 --training_steps=7000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="LHS" --seed=3 --env_name="cartdoublepole" --dt=.05 --alternations=10 --training_steps=7000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="LHS" --seed=4 --env_name="cartdoublepole" --dt=.05 --alternations=10 --training_steps=7000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="LHS" --seed=5 --env_name="cartdoublepole" --dt=.05 --alternations=10 --training_steps=7000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="LHS" --seed=6 --env_name="cartdoublepole" --dt=.05 --alternations=10 --training_steps=7000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="LHS" --seed=7 --env_name="cartdoublepole" --dt=.05 --alternations=10 --training_steps=7000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="LHS" --seed=8 --env_name="cartdoublepole" --dt=.05 --alternations=10 --training_steps=7000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="LHS" --seed=9 --env_name="cartdoublepole" --dt=.05 --alternations=10 --training_steps=7000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=3.
python run.py --utility_function="LHS" --seed=10 --env_name="cartdoublepole" --dt=.05 --alternations=10 --training_steps=7000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=3.
python run.py --oracle True --task_budget=0 --seed=1 --env_name="cartdoublepole" --dt=.05 --alternations=10 --training_steps=7000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=3.
python run.py --oracle True --task_budget=0 --seed=2 --env_name="cartdoublepole" --dt=.05 --alternations=10 --training_steps=7000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=3.
python run.py --oracle True --task_budget=0 --seed=3 --env_name="cartdoublepole" --dt=.05 --alternations=10 --training_steps=7000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=3.
python run.py --oracle True --task_budget=0 --seed=4 --env_name="cartdoublepole" --dt=.05 --alternations=10 --training_steps=7000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=3.
python run.py --oracle True --task_budget=0 --seed=5 --env_name="cartdoublepole" --dt=.05 --alternations=10 --training_steps=7000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=3.
python run.py --oracle True --task_budget=0 --seed=6 --env_name="cartdoublepole" --dt=.05 --alternations=10 --training_steps=7000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=3.
python run.py --oracle True --task_budget=0 --seed=7 --env_name="cartdoublepole" --dt=.05 --alternations=10 --training_steps=7000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=3.
python run.py --oracle True --task_budget=0 --seed=8 --env_name="cartdoublepole" --dt=.05 --alternations=10 --training_steps=7000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=3.
python run.py --oracle True --task_budget=0 --seed=9 --env_name="cartdoublepole" --dt=.05 --alternations=10 --training_steps=7000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=3.
python run.py --oracle True --task_budget=0 --seed=10 --env_name="cartdoublepole" --dt=.05 --alternations=10 --training_steps=7000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=3.

# experiment (ii) cart-pole
python run.py --utility_function="PAML" --seed=1 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.4 --config_interval_upper_bound_dim_1=3. --under_specified_system True --unobserved_parameter_lower_bound_dim_1=.4 --unobserved_parameter_upper_bound_dim_1=3. --observed_config_space_dim=1
python run.py --utility_function="PAML" --seed=2 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.4 --config_interval_upper_bound_dim_1=3. --under_specified_system True --unobserved_parameter_lower_bound_dim_1=.4 --unobserved_parameter_upper_bound_dim_1=3. --observed_config_space_dim=1
python run.py --utility_function="PAML" --seed=3 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.4 --config_interval_upper_bound_dim_1=3. --under_specified_system True --unobserved_parameter_lower_bound_dim_1=.4 --unobserved_parameter_upper_bound_dim_1=3. --observed_config_space_dim=1
python run.py --utility_function="PAML" --seed=4 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.4 --config_interval_upper_bound_dim_1=3. --under_specified_system True --unobserved_parameter_lower_bound_dim_1=.4 --unobserved_parameter_upper_bound_dim_1=3. --observed_config_space_dim=1
python run.py --utility_function="PAML" --seed=5 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.4 --config_interval_upper_bound_dim_1=3. --under_specified_system True --unobserved_parameter_lower_bound_dim_1=.4 --unobserved_parameter_upper_bound_dim_1=3. --observed_config_space_dim=1
python run.py --utility_function="PAML" --seed=6 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.4 --config_interval_upper_bound_dim_1=3. --under_specified_system True --unobserved_parameter_lower_bound_dim_1=.4 --unobserved_parameter_upper_bound_dim_1=3. --observed_config_space_dim=1
python run.py --utility_function="PAML" --seed=7 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.4 --config_interval_upper_bound_dim_1=3. --under_specified_system True --unobserved_parameter_lower_bound_dim_1=.4 --unobserved_parameter_upper_bound_dim_1=3. --observed_config_space_dim=1
python run.py --utility_function="PAML" --seed=8 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.4 --config_interval_upper_bound_dim_1=3. --under_specified_system True --unobserved_parameter_lower_bound_dim_1=.4 --unobserved_parameter_upper_bound_dim_1=3. --observed_config_space_dim=1
python run.py --utility_function="PAML" --seed=9 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.4 --config_interval_upper_bound_dim_1=3. --under_specified_system True --unobserved_parameter_lower_bound_dim_1=.4 --unobserved_parameter_upper_bound_dim_1=3. --observed_config_space_dim=1
python run.py --utility_function="PAML" --seed=10 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.4 --config_interval_upper_bound_dim_1=3. --under_specified_system True --unobserved_parameter_lower_bound_dim_1=.4 --unobserved_parameter_upper_bound_dim_1=3. --observed_config_space_dim=1
python run.py --utility_function="UNI" --seed=1 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.4 --config_interval_upper_bound_dim_1=3. --under_specified_system True --unobserved_parameter_lower_bound_dim_1=.4 --unobserved_parameter_upper_bound_dim_1=3. --observed_config_space_dim=1
python run.py --utility_function="UNI" --seed=2 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.4 --config_interval_upper_bound_dim_1=3. --under_specified_system True --unobserved_parameter_lower_bound_dim_1=.4 --unobserved_parameter_upper_bound_dim_1=3. --observed_config_space_dim=1
python run.py --utility_function="UNI" --seed=3 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.4 --config_interval_upper_bound_dim_1=3. --under_specified_system True --unobserved_parameter_lower_bound_dim_1=.4 --unobserved_parameter_upper_bound_dim_1=3. --observed_config_space_dim=1
python run.py --utility_function="UNI" --seed=4 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.4 --config_interval_upper_bound_dim_1=3. --under_specified_system True --unobserved_parameter_lower_bound_dim_1=.4 --unobserved_parameter_upper_bound_dim_1=3. --observed_config_space_dim=1
python run.py --utility_function="UNI" --seed=5 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.4 --config_interval_upper_bound_dim_1=3. --under_specified_system True --unobserved_parameter_lower_bound_dim_1=.4 --unobserved_parameter_upper_bound_dim_1=3. --observed_config_space_dim=1
python run.py --utility_function="UNI" --seed=6 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.4 --config_interval_upper_bound_dim_1=3. --under_specified_system True --unobserved_parameter_lower_bound_dim_1=.4 --unobserved_parameter_upper_bound_dim_1=3. --observed_config_space_dim=1
python run.py --utility_function="UNI" --seed=7 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.4 --config_interval_upper_bound_dim_1=3. --under_specified_system True --unobserved_parameter_lower_bound_dim_1=.4 --unobserved_parameter_upper_bound_dim_1=3. --observed_config_space_dim=1
python run.py --utility_function="UNI" --seed=8 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.4 --config_interval_upper_bound_dim_1=3. --under_specified_system True --unobserved_parameter_lower_bound_dim_1=.4 --unobserved_parameter_upper_bound_dim_1=3. --observed_config_space_dim=1
python run.py --utility_function="UNI" --seed=9 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.4 --config_interval_upper_bound_dim_1=3. --under_specified_system True --unobserved_parameter_lower_bound_dim_1=.4 --unobserved_parameter_upper_bound_dim_1=3. --observed_config_space_dim=1
python run.py --utility_function="UNI" --seed=10 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.4 --config_interval_upper_bound_dim_1=3. --under_specified_system True --unobserved_parameter_lower_bound_dim_1=.4 --unobserved_parameter_upper_bound_dim_1=3. --observed_config_space_dim=1
python run.py --utility_function="LHS" --seed=1 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.4 --config_interval_upper_bound_dim_1=3. --under_specified_system True --unobserved_parameter_lower_bound_dim_1=.4 --unobserved_parameter_upper_bound_dim_1=3. --observed_config_space_dim=1
python run.py --utility_function="LHS" --seed=2 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.4 --config_interval_upper_bound_dim_1=3. --under_specified_system True --unobserved_parameter_lower_bound_dim_1=.4 --unobserved_parameter_upper_bound_dim_1=3. --observed_config_space_dim=1
python run.py --utility_function="LHS" --seed=3 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.4 --config_interval_upper_bound_dim_1=3. --under_specified_system True --unobserved_parameter_lower_bound_dim_1=.4 --unobserved_parameter_upper_bound_dim_1=3. --observed_config_space_dim=1
python run.py --utility_function="LHS" --seed=4 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.4 --config_interval_upper_bound_dim_1=3. --under_specified_system True --unobserved_parameter_lower_bound_dim_1=.4 --unobserved_parameter_upper_bound_dim_1=3. --observed_config_space_dim=1
python run.py --utility_function="LHS" --seed=5 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.4 --config_interval_upper_bound_dim_1=3. --under_specified_system True --unobserved_parameter_lower_bound_dim_1=.4 --unobserved_parameter_upper_bound_dim_1=3. --observed_config_space_dim=1
python run.py --utility_function="LHS" --seed=6 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.4 --config_interval_upper_bound_dim_1=3. --under_specified_system True --unobserved_parameter_lower_bound_dim_1=.4 --unobserved_parameter_upper_bound_dim_1=3. --observed_config_space_dim=1
python run.py --utility_function="LHS" --seed=7 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.4 --config_interval_upper_bound_dim_1=3. --under_specified_system True --unobserved_parameter_lower_bound_dim_1=.4 --unobserved_parameter_upper_bound_dim_1=3. --observed_config_space_dim=1
python run.py --utility_function="LHS" --seed=8 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.4 --config_interval_upper_bound_dim_1=3. --under_specified_system True --unobserved_parameter_lower_bound_dim_1=.4 --unobserved_parameter_upper_bound_dim_1=3. --observed_config_space_dim=1
python run.py --utility_function="LHS" --seed=9 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.4 --config_interval_upper_bound_dim_1=3. --under_specified_system True --unobserved_parameter_lower_bound_dim_1=.4 --unobserved_parameter_upper_bound_dim_1=3. --observed_config_space_dim=1
python run.py --utility_function="LHS" --seed=10 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.4 --config_interval_upper_bound_dim_1=3. --under_specified_system True --unobserved_parameter_lower_bound_dim_1=.4 --unobserved_parameter_upper_bound_dim_1=3. --observed_config_space_dim=1
python run.py --oracle True --task_budget=0 --seed=1 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.4 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.4 --config_interval_upper_bound_dim_2=3.
python run.py --oracle True --task_budget=0 --seed=2 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.4 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.4 --config_interval_upper_bound_dim_2=3.
python run.py --oracle True --task_budget=0 --seed=3 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.4 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.4 --config_interval_upper_bound_dim_2=3.
python run.py --oracle True --task_budget=0 --seed=4 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.4 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.4 --config_interval_upper_bound_dim_2=3.
python run.py --oracle True --task_budget=0 --seed=5 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.4 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.4 --config_interval_upper_bound_dim_2=3.
python run.py --oracle True --task_budget=0 --seed=6 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.4 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.4 --config_interval_upper_bound_dim_2=3.
python run.py --oracle True --task_budget=0 --seed=7 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.4 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.4 --config_interval_upper_bound_dim_2=3.
python run.py --oracle True --task_budget=0 --seed=8 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.4 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.4 --config_interval_upper_bound_dim_2=3.
python run.py --oracle True --task_budget=0 --seed=9 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.4 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.4 --config_interval_upper_bound_dim_2=3.
python run.py --oracle True --task_budget=0 --seed=10 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.4 --config_interval_upper_bound_dim_1=3. --config_interval_lower_bound_dim_2=.4 --config_interval_upper_bound_dim_2=3.

# experiment (iii) cart-pole
python run.py --utility_function="PAML" --seed=1 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2. --config_interval_lower_bound_dim_3=.5 --config_interval_upper_bound_dim_3=5. --over_specified_system True --observed_config_space_dim=3
python run.py --utility_function="PAML" --seed=2 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2. --config_interval_lower_bound_dim_3=.5 --config_interval_upper_bound_dim_3=5. --over_specified_system True --observed_config_space_dim=3
python run.py --utility_function="PAML" --seed=3 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2. --config_interval_lower_bound_dim_3=.5 --config_interval_upper_bound_dim_3=5. --over_specified_system True --observed_config_space_dim=3
python run.py --utility_function="PAML" --seed=3 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2. --config_interval_lower_bound_dim_3=.5 --config_interval_upper_bound_dim_3=5. --over_specified_system True --observed_config_space_dim=3
python run.py --utility_function="PAML" --seed=3 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2. --config_interval_lower_bound_dim_3=.5 --config_interval_upper_bound_dim_3=5. --over_specified_system True --observed_config_space_dim=3
python run.py --utility_function="PAML" --seed=4 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2. --config_interval_lower_bound_dim_3=.5 --config_interval_upper_bound_dim_3=5. --over_specified_system True --observed_config_space_dim=3
python run.py --utility_function="PAML" --seed=5 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2. --config_interval_lower_bound_dim_3=.5 --config_interval_upper_bound_dim_3=5. --over_specified_system True --observed_config_space_dim=3
python run.py --utility_function="PAML" --seed=6 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2. --config_interval_lower_bound_dim_3=.5 --config_interval_upper_bound_dim_3=5. --over_specified_system True --observed_config_space_dim=3
python run.py --utility_function="PAML" --seed=7 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2. --config_interval_lower_bound_dim_3=.5 --config_interval_upper_bound_dim_3=5. --over_specified_system True --observed_config_space_dim=3
python run.py --utility_function="PAML" --seed=8 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2. --config_interval_lower_bound_dim_3=.5 --config_interval_upper_bound_dim_3=5. --over_specified_system True --observed_config_space_dim=3
python run.py --utility_function="PAML" --seed=9 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2. --config_interval_lower_bound_dim_3=.5 --config_interval_upper_bound_dim_3=5. --over_specified_system True --observed_config_space_dim=3
python run.py --utility_function="PAML" --seed=10 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2. --config_interval_lower_bound_dim_3=.5 --config_interval_upper_bound_dim_3=5. --over_specified_system True --observed_config_space_dim=3
python run.py --utility_function="UNI" --seed=1 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2. --config_interval_lower_bound_dim_3=.5 --config_interval_upper_bound_dim_3=5. --over_specified_system True --observed_config_space_dim=3
python run.py --utility_function="UNI" --seed=2 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2. --config_interval_lower_bound_dim_3=.5 --config_interval_upper_bound_dim_3=5. --over_specified_system True --observed_config_space_dim=3
python run.py --utility_function="UNI" --seed=3 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2. --config_interval_lower_bound_dim_3=.5 --config_interval_upper_bound_dim_3=5. --over_specified_system True --observed_config_space_dim=3
python run.py --utility_function="UNI" --seed=4 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2. --config_interval_lower_bound_dim_3=.5 --config_interval_upper_bound_dim_3=5. --over_specified_system True --observed_config_space_dim=3
python run.py --utility_function="UNI" --seed=5 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2. --config_interval_lower_bound_dim_3=.5 --config_interval_upper_bound_dim_3=5. --over_specified_system True --observed_config_space_dim=3
python run.py --utility_function="UNI" --seed=6 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2. --config_interval_lower_bound_dim_3=.5 --config_interval_upper_bound_dim_3=5. --over_specified_system True --observed_config_space_dim=3
python run.py --utility_function="UNI" --seed=7 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2. --config_interval_lower_bound_dim_3=.5 --config_interval_upper_bound_dim_3=5. --over_specified_system True --observed_config_space_dim=3
python run.py --utility_function="UNI" --seed=8 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2. --config_interval_lower_bound_dim_3=.5 --config_interval_upper_bound_dim_3=5. --over_specified_system True --observed_config_space_dim=3
python run.py --utility_function="UNI" --seed=9 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2. --config_interval_lower_bound_dim_3=.5 --config_interval_upper_bound_dim_3=5. --over_specified_system True --observed_config_space_dim=3
python run.py --utility_function="UNI" --seed=10 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2. --config_interval_lower_bound_dim_3=.5 --config_interval_upper_bound_dim_3=5. --over_specified_system True --observed_config_space_dim=3
python run.py --utility_function="LHS" --seed=1 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2. --config_interval_lower_bound_dim_3=.5 --config_interval_upper_bound_dim_3=5. --over_specified_system True --observed_config_space_dim=3
python run.py --utility_function="LHS" --seed=2 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2. --config_interval_lower_bound_dim_3=.5 --config_interval_upper_bound_dim_3=5. --over_specified_system True --observed_config_space_dim=3
python run.py --utility_function="LHS" --seed=3 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2. --config_interval_lower_bound_dim_3=.5 --config_interval_upper_bound_dim_3=5. --over_specified_system True --observed_config_space_dim=3
python run.py --utility_function="LHS" --seed=4 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2. --config_interval_lower_bound_dim_3=.5 --config_interval_upper_bound_dim_3=5. --over_specified_system True --observed_config_space_dim=3
python run.py --utility_function="LHS" --seed=5 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2. --config_interval_lower_bound_dim_3=.5 --config_interval_upper_bound_dim_3=5. --over_specified_system True --observed_config_space_dim=3
python run.py --utility_function="LHS" --seed=6 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2. --config_interval_lower_bound_dim_3=.5 --config_interval_upper_bound_dim_3=5. --over_specified_system True --observed_config_space_dim=3
python run.py --utility_function="LHS" --seed=7 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2. --config_interval_lower_bound_dim_3=.5 --config_interval_upper_bound_dim_3=5. --over_specified_system True --observed_config_space_dim=3
python run.py --utility_function="LHS" --seed=8 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2. --config_interval_lower_bound_dim_3=.5 --config_interval_upper_bound_dim_3=5. --over_specified_system True --observed_config_space_dim=3
python run.py --utility_function="LHS" --seed=9 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2. --config_interval_lower_bound_dim_3=.5 --config_interval_upper_bound_dim_3=5. --over_specified_system True --observed_config_space_dim=3
python run.py --utility_function="LHS" --seed=10 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2. --config_interval_lower_bound_dim_3=.5 --config_interval_upper_bound_dim_3=5. --over_specified_system True --observed_config_space_dim=3
python run.py --oracle True --task_budget=0 --seed=1 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --oracle True --task_budget=0 --seed=2 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --oracle True --task_budget=0 --seed=3 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --oracle True --task_budget=0 --seed=4 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --oracle True --task_budget=0 --seed=5 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --oracle True --task_budget=0 --seed=6 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --oracle True --task_budget=0 --seed=7 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --oracle True --task_budget=0 --seed=8 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --oracle True --task_budget=0 --seed=9 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.
python run.py --oracle True --task_budget=0 --seed=10 --env_name="cartpole" --dt=.125 --alternations=10 --training_steps=5000 --n_initial_training_envs=3 --config_interval_lower_bound_dim_1=.5 --config_interval_upper_bound_dim_1=5. --config_interval_lower_bound_dim_2=.5 --config_interval_upper_bound_dim_2=2.